# Generated by Django 6.0.1 on 2026-06-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance')], max_length=20),
        ),
    ]
